import os
import sys
import math
from snakemake.utils import min_version

min_version("6.0")

SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))
shell.prefix(f"set -eo pipefail;")


report: "report/workflow.rst"


configfile: "config/config.yaml"


MANIFEST = config.get('MANIFEST', 'config/manifest.tab')
BASECALL_VERSION = config.get('BASECALLER', 'guppy5012')
REF = config.get('REF', '/net/eichler/vol26/eee_shared/assemblies/hg38/no_alt/hg38.no_alt.fa')
NBATCHES = config.get('BATCHES', 100)
CLAIR_DIR = config.get('clair_dir', '/net/eichler/vol26/7200/software/pipelines/clair3')


manifest_df = pd.read_csv(MANIFEST, sep='\t', index_col='SAMPLE')


TEMP_DIR = config.pop("tempdir", "temp")
if TEMP_DIR != "temp":
    if os.path.exists("temp"):
        if os.path.islink("temp") and os.path.realpath("temp") == os.path.realpath(
            TEMP_DIR
        ):
            print("The temp dir has already been linked.")
        else:
            sys.exit("temp/ already in use, please move it before running.")
    else:
        shell("ln -s {TEMP_DIR} temp")


localrules: all, clair


rule all:
    input:
        expand('alignments/{sample}/{sample}.{bc_vers}.minimap2.{seq}.{var_caller}.vcf.gz', sample=manifest_df.index, bc_vers=BASECALL_VERSION, seq='wgs', var_caller=['sniffles', 'svim', 'cuteSV', 'clair3']),

include('rules/alignment.smk')
include('rules/variant_calling.smk')
